#################################################################################################
# Grade service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: grade-service 
  labels:
    app: grade-service 
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: grade-service 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grade-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grade-service 
        version: v1
    spec:
      containers:
      - name: grade-service 
        image: grade-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/grades
        backend:
          serviceName: grade-service 
          servicePort: 8080
---